### PR TITLE
Removing DOE image

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by djw8605** [comment]
No, not really.  Though we would have to change a few other classes such that it still works, but that's not a huge deal.

**Comment by djw8605** [comment]
@brianhlin Changes made

**Comment by djw8605** [comment]
@brianhlin re-review please

**Comment by brianhlin** [comment]
I looked at this briefly when you made your last change but couldn't find the `offset4` class. I don't think I'll get to this before I leave so I'm requesting a review from @matyasselmeci.

**Comment by matyasselmeci** [comment]
Is this running anywhere such that I can look at it? If not, can you attach a screenshot?

**Comment by djw8605** [comment]
This change is running in production at https://display.opensciencegrid.org/

**Comment by matyasselmeci** [comment]
Well, if it's already running in production, then we can merge it can't we.

**Pull request merged**
